### ISSUE TITLE
Secret credentials format

### ISSUE THREAD

**Issue by driosalido** [corewire/provider-keycloak#1]
Hi! I'm trying to use the provider but I don't know how to provide the keycloak credentials through a kubernetes secret. Could you please share an example?

Thanks!

**Comment by Breee** [comment]
Greetings, 

the latest version of the provider is here: https://github.com/crossplane-contrib/provider-keycloak 

however: 

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
type: Opaque
stringData:
  credentials: |
    {
      "client_id": "xxxxxx",
      "client_secret": "xxxxxx",
      "url": "https://keycloak.example.com",
      "base_path": "/auth",
      "realm": "master"
    }   
```

```
---
apiVersion: keycloak.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: keycloak-config
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: keycloak-credentials
      key: credentials
      namespace: crossplane-system
```

added it here: https://github.com/crossplane-contrib/provider-keycloak/blob/main/examples/credentials.yaml
